openshift/machine-api-provider-powervs

.gitignore, Dockerfile, Makefile
This PR contains following changes
1. Updated docker image used to build targets to go 1.17
2. Update Docker file to fix make images failure
3. Added .idea directory generated by GoLand IDE to gitignor file
=> Updated Makefile

pkg/actuators/machine/reconciler.go, pkg/actuators/machine/reconciler_test.go
Currently the zone, region and instance type labels are not set to the machines so the information is not displayed when we are querying for machine resources in cluster
```
karthikkn@Karthiks-MacBook-Pro cluster-api % oc get machine -A
NAMESPACE               NAME                                     PHASE     TYPE   REGION   ZONE   AGE
openshift-machine-api   powervs-actuator-testing-machine-dwbnj   Running                          30m
openshift-machine-api   rdr-kabhat-mrl5n-master-0                Running                          5d5h
openshift-machine-api   rdr-kabhat-mrl5n-master-1                Running                          5d5h
openshift-machine-api   rdr-kabhat-mrl5n-master-2                Running                          5d5h
openshift-machine-api …
```
=> Set zone, region labels to machines

pkg/actuators/machine/actuator_test.go, pkg/actuators/machine/instances.go, pkg/actuators/machine/machine_scope.go, pkg/actuators/machine/reconciler.go, pkg/actuators/machine/reconciler_test.go, pkg/actuators/machine/stubs.go, pkg/apis/powervsprovider/v1alpha1/powervsmachineproviderstatus_types.go, pkg/apis/powervsprovider/v1alpha1/zz_generated.deepcopy.go
This PR contains following changes
1. To fix the ProviderID format when ServiceInstance.ID or ServiceInstance.Name is passed in spec 
2. Storing the ServiceInstanceID in machine status so that it can be easily fetched against making a query to Power Cloud
3. Storing the ServiceInstanceID in status field so that user will not edit
Fixes: [15](https://github.com/openshift/machine-api-provider-powervs/issues/15)
=> Fixed Provider ID format

cmd/manager/main.go, pkg/actuators/machine/actuator.go, pkg/actuators/machine/actuator_test.go, pkg/actuators/machine/caching.go, pkg/actuators/machine/machine_scope.go, pkg/actuators/machine/reconciler.go, pkg/actuators/machine/reconciler_test.go, pkg/actuators/machine/stubs.go, pkg/client/client.go, pkg/client/mock/client_generated.go, pkg/client/powervs_client.go
Main intention of this PR is to set the NodeInternalIP for machine so that the cluster auto approver will approve the server csr requests
1. With DHCP server in place , The IP of the machine needs to fetched from dhcp server lease using the VM mac address
2. Also a cache implementation is added to avoid frequent calls to DHCP server
=> Bug 2100033: Fetch VM IP from DHCP server to set NodeInternalIP

pkg/actuators/machine/reconciler.go, pkg/actuators/machine/reconciler_test.go
This PR contains the change to atleset set the node internal dns address even if failed to set the internal ip.
More context: Recently while testing i found that in some instances its not able to find a IP from dhcp server as there was no lease exist which leading it not to set any address for machine, Later once the machine is provisioned without any address being set, the client csr was never approved and machine never became a node.
=> Set the node internal dns address for machine

cmd/manager/main.go, pkg/controllers/custom_service_endpoint_controller.go, pkg/controllers/custom_service_endpoint_controller_test.go
Controller to sync the custom service endpoints from spec field of infrastructure object to status field.
openshift/api PR to add ServiceEndpoints: https://github.com/openshift/api/pull/1025
Its originally started from https://github.com/openshift/cluster-config-operator/pull/256
=> Add infrastructure sync controller for custom service endpoints

pkg/actuators/machine/reconciler.go
This PR removes the full error from the Reason field in RegisterFailedInstanceXXXX metrics, because it was causing the metric to have high/unbound cardinality. The full error is still logged, so this PR should not affect the ability to troubleshoot issues.
=> OCPBUGS-11223: Reduce metrics cardinality

Makefile
Updated golang version used for running tests
Updated podman command to remove :Z as its not supported
=> MULTIARCH-3668: Update make file to use latest golang

pkg/actuators/machine/reconciler.go, pkg/actuators/machine/reconciler_test.go, pkg/actuators/machine/stubs.go, pkg/actuators/machine/utils.go, pkg/client/powervs_client.go
It will take few seconds for the newly created vm to be available in getAllInstaces() but we can fetch the vm directly if we know the instance id.
As a part of this PR we are setting that vm is in build condition and as a part of it [instance id will be set in provider status](https://github.com/Karthik-K-N/machine-api-provider-powervs/blob/da14713a9e2c5b27bb00383a4f5d08b15908bc58/pkg/actuators/machine/machine_scope.go#L169-L175).
Later it will help in exists() method to[ fetch the vm by instance id](https://github.com/Karthik-K-N/machine-api-provider-powervs/blob/473070f9045e7a6e83167076680067beb2b169f0/pkg/actuators/machine/reconciler.go#L326-L334).
=> MULTIARCH-3669:  Set instance build condition to avoid attempting to create duplicate vm with same name

pkg/client/powervs_client.go
The funciton GetNextStart() can return nil.  Therefore handle it.
=> Fix nil nextURL

pkg/actuators/machine/utils.go, pkg/client/powervs_client.go
When you pass in endpoints in install config:
```
serviceEndpoints:
- name: dnsservices
url: https://api.dns-svcs.cloud.ibm.com
- name: cos
url: https://s3.us-south.cloud-object-storage.appdomain.cloud
```
You see the following error:
```
failed creating minimalPowerVS client Error: setenv: invalid argument
```
Add some more endpoint mapping.  Also, return an error if an endpoint is not known.
=> OCPBUGS-33995: Add more custom endpoints

go.mod, go.sum, vendor/github.com/ppc64le-cloud/powervs-utils/region.go, vendor/modules.txt
powervs-utils now supports two new zones. Update the version of powervs-utils used to include these.
=> MULTIARCH-5163: Update powervs-utils regions to include us-south and tor

pkg/client/powervs_client.go
Like #95, this one is to properly use override URL for `ResourceController`, if provided. With this running locally, it is verified that the cluster would be able to provision worker VMs.
=> OCPBUGS-47476: Overrides URL for ResourceController client if provided

pkg/client/powervs_client.go
Like #97, this PR applies the same treatment for `ResourceController` endpoint override honoring it in `NewValidatedClient()`.
=> OCPBUGS-47764: Honors custom ResourceController endpoint URL in NewValidatedClient(), if provided

pkg/client/powervs_client.go
`control-plane-machine-set` CO needs this in Disconnected scenario in order to become `Available` by finding LBs, VSIs, etc. properly at the "private" endpoint (with `/v1` at the end).
Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>
=> OCPBUGS-49733: Uses VPC endpoint override in Disconnected case

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
cherry-pick upstream Ref - PR #111 
Affected Library: `github.com/golang-jwt/jwt/v4`
Current Version: `v4.5.0`
Fixed Version: `v4.5.2`
=> OCPBUGS-54750: Fix for CVE-2024-51744 in github.com/golang-jwt/jwt/v4 in release-4.17

Makefile
This change is motivated by the [slack discussion](https://redhat-internal.slack.com/archives/CB95J6R4N/p1749170294911329) in which it appears that Konflux system might need to recover the git version in a different way than what we traditionally used. 
This change might help with 4.20 images being wrongly labeled as explained in the thread
=> NO-ISSUE: Use OS_GIT_VERSION in Makefile when found (for Konflux builds)

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
cherry-pick upstream Ref - PR https://github.com/openshift/machine-api-provider-powervs/pull/111
Affected Library: `github.com/golang-jwt/jwt/v4`
Current Version: `v4.5.0`
Fixed Version: `v4.5.2`
=> OCPBUGS-54753: Fix for CVE-2024-51744 in github.com/golang-jwt/jwt/v4 in release-4.15

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
cherry-pick upstream Ref - PR https://github.com/openshift/machine-api-provider-powervs/pull/111
Affected Library: `github.com/golang-jwt/jwt/v4`
Current Version: `v4.5.0`
Fixed Version: `v4.5.2`
=> OCPBUGS-54754: Fix for CVE-2024-51744 in github.com/golang-jwt/jwt/v4 in release-4.14

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/README.md, vendor/github.com/golang-jwt/jwt/v4/SECURITY.md, vendor/github.com/golang-jwt/jwt/v4/claims.go, vendor/github.com/golang-jwt/jwt/v4/errors.go, vendor/github.com/golang-jwt/jwt/v4/map_claims.go, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v4/parser_option.go, vendor/github.com/golang-jwt/jwt/v4/rsa_pss.go, vendor/github.com/golang-jwt/jwt/v4/token.go, vendor/github.com/golang-jwt/jwt/v4/types.go, vendor/modules.txt
cherry-pick upstream Ref - PR https://github.com/openshift/machine-api-provider-powervs/pull/111
Affected Library: github.com/golang-jwt/jwt/v4
Fixed Version: v4.5.2
=> OCPBUGS-54013: Fix for CVE-2025-30204 & CVE-2024-51744 in github.com/golang-jwt/jwt/v4 in release-4.13
